Minor/Minor/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('story.urls', namespace='story')),
    url(r'^', include('account.urls', namespace='user')),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Minor/account/urls.py
from django.conf.urls import url
from . import signals

from .views import *


urlpatterns = [
    url(r'^accounts/signup/$', Signup.as_view(), name='signup'),
    url(r'^accounts/signin/$', Signin.as_view(), name='signin'),
    url(r'^accounts/signout/$', Signout.as_view(), name='signout'),
    url(r'^@(?P<slug>[\w-]+)/$', Profile.as_view(), name="profile"),
    url(r'^@(?P<slug>[\w-]+)/update/$', Update.as_view(), name="update"),




]

Minor/story/urls.py
from django.conf.urls import url
from . import signals

from .views import *

urlpatterns = [
    url(r'^$', Index.as_view(), name='index'),
    url(r'^home/$', Home.as_view(), name='home'),
    url(r'^aboutus/$', About.as_view(), name='about'),
    url(r'^contactus/$', Contact.as_view(), name='contact'),
    url(r'^story/trending/$', Trending.as_view(), name='trending'),
    url(r'^story/recommended/$', Recommended.as_view(), name='recommended'),
    url(r'^@(?P<author_slug>[\w-]+)/story/create/$',
        Create.as_view(), name='create'),
    url(r'^(?P<story_slug>[\w-]+)/update/$',
        Update.as_view(), name='update'),
    url(r'^(?P<story_slug>[\w-]+)/$',
        Detail.as_view(), name='detail'),
    url(r'^(?P<story_slug>[\w-]+)/delete$',
        Delete.as_view(), name='delete'),

]

Minor/templates/about.html
{% extends 'base.html' %}
{%load staticfiles%}
{% block head_title %}About Us | {{ block.super }} {% endblock head_title %}

{% block main %}
<!-- Content -->
        <div class="page-about">
            <!-- About me header -->
            <header class="pagesHeader aboutHeader aboutUsHeader">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12 col-sm-6 col-sm-offset-3 col-lg-4 col-lg-offset-4">
                            <h1><span>About us</span></h1>
                            <h2>Everything you need to know about Us</h2>
                        </div>
                    </div>
                </div>
            </header>
            <!-- About me text -->
            <div class="aboutText rte">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12 col-sm-4">
                            <h2>What we do</h2>
                            <p>Donec hendrerit risus eros, ac dictum nulla ornare vitae. Maecenas vitae condimentum dolor, vitae facilisis justo. Morbi tristique pretium odio, fermentum molestie erat. Nunc quis aliquam ligula. Fusce et odio ligula.</p>
                        </div>
                        <div class="col-xs-12 col-sm-4">
                            <h2>Our mission</h2>
                            <p>Nam elementum orci ullamcorper leo ultricies, vel consequat ligula dictum. Donec ut tellus vulputate, viverra nisi accumsan, viverra elit. Nam sed bibendum turpis. Aenean porta rutrum iaculis.</p>
                        </div>
                        <div class="col-xs-12 col-sm-4">
                            <h2>Our Philosophy</h2>
                            <p> Integer efficitur, nunc quis volutpat pretium, ligula ligula tincidunt sem, ac ullamcorper felis tortor eget mi. Mauris vel sollicitudin purus. Suspendisse et neque vel ante pharetra finibus.</p>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Our team -->
            <div class="ourTeamSection">
                <div class="container">
                    <header class="pagesHeader">
                        <div class="row">
                            <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3">
                                <h1 class="separator-gray"><span>Our Team</span></h1>
                                <h2>Duis ex lectus, hendrerit ut lacus quis, viverra faucibus tellus.</h2>
                            </div>
                        </div>
                    </header>
                    <div class="row">
                        <div class="col-xs-12 col-sm-4 i">
                            <a href="#" title="#">
                                <img src="{% static 'tmp/270x300-1.jpg' %}" alt="#" width="270" height="300" class="img-responsive">
                            </a>
                            <h3 class="name">
                                <a href="#" title="#">Aakash Shrestha</a>
                            </h3>
                            <h4 class="position">Creative Director</h4>
                            <p>Suspendisse et neque vel ante pharetra finibus. Sed diam leo <a href="#" title="#">\+\</a></p>
                            <div class="socials">
                                <a href="#" title="#"><i class="fa fa-twitter"></i></a>
                                <a href="#" title="#"><i class="fa fa-facebook"></i></a>
                                <a href="#" title="#"><i class="fa fa-google-plus"></i></a>
                                <a href="#" title="#"><i class="fa fa-linkedin"></i></a>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-4 i">
                            <a href="#" title="#">
                                <img src="{% static 'tmp/270x300-2.jpg' %}" alt="#" width="270" height="300" class="img-responsive">
                            </a>
                            <h3 class="name">
                                <a href="#" title="#">Pujan Fucche</a>
                            </h3>
                            <h4 class="position">Technical Director</h4>
                            <p>Etiam vulputate, nisl eu cursus eleme tum, libero odio euismod ligula <a href="#" title="#">\+\</a></p>
                            <div class="socials">
                                <a href="#" title="#"><i class="fa fa-twitter"></i></a>
                                <a href="#" title="#"><i class="fa fa-facebook"></i></a>
                                <a href="#" title="#"><i class="fa fa-google-plus"></i></a>
                                <a href="#" title="#"><i class="fa fa-linkedin"></i></a>
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-4 i">
                            <a href="#" title="#">
                                <img src="{% static 'tmp/270x300-3.jpg' %}" alt="#" width="270" height="300" class="img-responsive">
                            </a>
                            <h3 class="name">
                                <a href="#" title="#">Raj Dangol</a>
                            </h3>
                            <h4 class="position">Art Director</h4>
                            <p>Quisque a felis vel libero ultricies tincidunt iaculis eget nunc phasellus <a href="#" title="#">\+\</a></p>
                            <div class="socials">
                                <a href="#" title="#"><i class="fa fa-twitter"></i></a>
                                <a href="#" title="#"><i class="fa fa-facebook"></i></a>
                                <a href="#" title="#"><i class="fa fa-google-plus"></i></a>
                                <a href="#" title="#"><i class="fa fa-linkedin"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Quotes -->
            <div class="quotesSection">
                <div class="container">
                    <header class="pagesHeader">
                        <div class="row">
                            <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2 col-lg-6 col-lg-offset-3">
                                <h1><span>Some Inspiring Quotes</span></h1>
                            </div>
                        </div>
                    </header>

                    <div class="rte text-center js-quotes-carousel">
                        <div class="i">
                            <blockquote class="blockquote-1">
                                Thousands of candles can be lighted from a single candle, and the life of the candle will not be shortened. Happiness never decreases by being shared.
                                <cite>Buddha</cite>
                            </blockquote>
                        </div>
                        <div class="i">
                            <blockquote class="blockquote-1">
                                The most common way people give up their power is by thinking they don’t have any.
                                <cite>Alice Walker</cite>
                            </blockquote>
                        </div>
                        <div class="i">
                            <blockquote class="blockquote-1">
                                Strive not to be a success, but rather to be of value.
                                <cite>Albert Einstein</cite>
                            </blockquote>
                        </div>
                        <div class="i">
                            <blockquote class="blockquote-1">
                                I’ve learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel.
                                <cite>Maya Angelou</cite>
                            </blockquote>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock main %}

Minor/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" conte{nt="width=device-width, initial-scale=1">
    <link rel="icon" href="{% static 'favicon.ico'%}">

  <title>
    {% block head_title %}StoryBook{% endblock head_title %}
  </title>

  <!-- CSS -->
	<link rel="stylesheet" href="{% static 'assets/bootstrap/css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'assets/css/owl.carousel.css'%}">
	<link rel="stylesheet" href="{% static 'assets/font-awesome/css/font-awesome.min.css'%}">
	<link rel="stylesheet" href="{% static 'assets/css/select2.min.css'%}">
	<link rel="stylesheet" href="{% static 'assets/css/app.min.css'%}">

	<!-- Modernizr -->
	<script src="{% static 'assets/js/modernizr-2.8.3.min.js'%}"></script>

	<!-- Google Fonts -->
	<link href='http://fonts.googleapis.com/css?family=Roboto+Slab:300,700,100,400' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Source+Code+Pro:200,300,400,500,600,700,900' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Raleway:500,600,700,100,800,900,400,200,300' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,100italic,300italic,400italic,700italic,900italic' rel='stylesheet' type='text/css'>

  {% block style %}{% endblock style %}

</head>
<body>
<div class="pageWrap">
  {% include 'header.html' %}
  {% block main %}{% endblock main %}
  {% include 'footer.html' %}
</div>


	<script src="{% static 'assets/js/jquery-2.2.3.min.js' %}"></script>
	<script src="{% static 'assets/bootstrap/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'assets/js/masonry.pkgd.min.js' %}"></script>
	<script src="{% static 'assets/js/underscore-min.js' %}"></script>
	<script src="{% static 'assets/js/moment-2.8.3.js' %}"></script>
	<script src="{% static 'assets/js/clndr.min.js' %}"></script>
	<script src="{% static 'assets/js/select2.min.js' %}"></script>
	<script src="{% static 'assets/js/jquery.dotdotdot.min.js' %}"></script>
	<script src="{% static 'assets/js/jquery.countdown.min.js' %}"></script>
	<script src="{% static 'assets/js/jquery.countTo.js' %}"></script>
	<script src="{% static 'assets/js/jquery.waypoints.min.js' %}"></script>
	<script src="{% static 'assets/js/jquery.easypiechart.min.js' %}"></script>
	<script src="{% static 'assets/js/jquery.magnific-popup.min.js' %}"></script>
	<script src="{% static 'assets/js/app.min.js' %}"></script>

<script type="text/javascript">
$(document).ready(function(){
    $(".comment-reply-btn").click(function(event){
        event.preventDefault();
        $(this).parent().next(".comment-reply").fadeToggle();
    })
})
</script>

	<!-- Calendar events -->
	<script>
		Calendar.events = [
			{ date: moment().format('2016-04-07'), url: '#' },
			{ date: moment().format('2016-04-08'), url: '#' },
			{ date: moment().format('2016-04-09'), url: '#' },
			{ date: moment().format('2016-04-23'), url: '#' },
			{ date: moment().format('2016-05-10'), url: '#' },
			{ date: moment().format('2016-05-14'), url: '#' },
			{ date: moment().format('2016-05-19'), url: '#' },
			{ date: moment().format('2016-05-28'), url: '#' },
			{ date: moment().format('2016-09-04'), url: '#' },
			{ date: moment().format('2016-09-09'), url: '#' },
			{ date: moment().format('2016-09-14'), url: '#' },
			{ date: moment().format('2016-09-17'), url: '#' },
			{ date: moment().format('2016-09-21'), url: '#' },
			{ date: moment().format('2016-09-26'), url: '#' },
			{ date: moment().format('2016-09-28'), url: '#' },
			{ date: moment().format('2016-10-04'), url: '#' },
			{ date: moment().format('2016-10-09'), url: '#' },
			{ date: moment().format('2016-10-14'), url: '#' },
			{ date: moment().format('2016-10-17'), url: '#' },
			{ date: moment().format('2016-10-21'), url: '#' },
			{ date: moment().format('2016-10-26'), url: '#' },
			{ date: moment().format('2016-10-28'), url: '#' },
			{ date: moment().format('2016-11-04'), url: '#' },
			{ date: moment().format('2016-11-09'), url: '#' },
			{ date: moment().format('2016-11-14'), url: '#' },
			{ date: moment().format('2016-11-17'), url: '#' },
			{ date: moment().format('2016-11-21'), url: '#' },
			{ date: moment().format('2016-11-26'), url: '#' },
			{ date: moment().format('2016-11-28'), url: '#' },
			{ date: moment().format('2016-12-04'), url: '#' },
			{ date: moment().format('2016-12-09'), url: '#' },
			{ date: moment().format('2016-12-14'), url: '#' },
			{ date: moment().format('2016-12-17'), url: '#' },
			{ date: moment().format('2016-12-21'), url: '#' },
			{ date: moment().format('2016-12-26'), url: '#' },
			{ date: moment().format('2016-12-28'), url: '#' },
		];
	</script>


</body>
</html>

Minor/templates/contact.html
{% extends 'base.html' %}

{% block head_title %}Contact Us | {{ block.super }} {% endblock head_title %}

{% block main %}

        <!-- Content -->
        <div class="page-contact">
            <!-- Contact us header -->
            <header class="pagesHeader contactHeader contactUsHeader">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12 col-sm-6 col-sm-offset-3 col-lg-4 col-lg-offset-4">
                            <h1><span>Contact us</span></h1>
                            <h2>Drop us a line</h2>
                        </div>
                    </div>
                </div>
            </header>

            <!-- Contact details -->
            <div class="contactDetails">
                <div class="container">
                    <div class="row">
                        <div class="col-xs-12 col-sm-4 i">
                            <i class="fa fa-map-marker icon"></i>
                            Pulchowk,<br />Lalitpur
                        </div>
                        <div class="col-xs-12 col-sm-4 i">
                            <i class="fa fa-envelope icon"></i>
                            <a href="mailto:hello@blogee.co" title="#">hello@bctians.com</a>
                        </div>
                        <div class="col-xs-12 col-sm-4 i">
                            <i class="fa fa-phone icon"></i>
                            +387 (0)33 25 43 62
                        </div>
                    </div>
                </div>
            </div>

            <!-- Contact form -->
            <div class="contactFormWrap customForms customForm">
                <div class="container">
                    <form>
                        <div class="row">
                            <div class="col-xs-12 col-sm-4 user">
                                <i class="fa fa-user icon"></i>
                                <input type="text" placeholder="Name" class="input">
                            </div>
                            <div class="col-xs-12 col-sm-4 misc">
                                <i class="fa fa-envelope icon"></i>
                                <input type="email" placeholder="E-mail" class="input">
                            </div>
                            <div class="col-xs-12 col-sm-4 misc">
                                <i class="fa fa-folder icon"></i>
                                <input type="text" placeholder="Subject" class="input">
                            </div>
                            <div class="col-xs-12 misc">
                                <i class="fa fa-comment icon"></i>
                                <textarea placeholder="Message" class="input"></textarea>
                            </div>

                            <div class="col-xs-12 text-center">
                                <button class="btn btn-color-full" type="submit"><span>Send</span></button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

            <!-- Google map -->
            <div id="googleMap" data-lat="27.6828" data-lng="85.3180" data-zoom="16"></div>
            <script src="https://maps.googleapis.com/maps/api/js?v=3.exp&amp;sensor=false"></script>
        </div>

{% endblock main %}

Minor/templates/footer.html
{% load staticfiles %}
<footer id="footer">
    <div class="logoWrap">
        <div class="container">
            <h1>
                <a href="{% url 'story:index' %}" title="#">
                    <img src="{% static 'img/logo.png'%}" alt="#" width="208" height="108" class="img-responsive">
                    <strong>StoryBook</strong>
                </a>
            </h1>
        </div>
    </div>

    <div class="copyright">
        <div class="container">
            Copyright @2016 Yours. All Rights Reserved.
        </div>
    </div>
</footer>

Minor/templates/header.html
{% load staticfiles %}

<header id="header">
    <!-- Main navigation bar -->
    <div class="navbar navbar-inverse">
        <div class="container">
            <!-- Mobile navbar toggler -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>

            <nav id="navbar" class="collapse navbar-collapse">
                <!-- Main navigation -->
                <ul class="nav navbar-nav navigation">
                    <li class="hoverExtend "><a href="{% url 'story:home' %}" title="#">Home</a></li>
                    <li class="hoverExtend "><a href="{% url 'story:trending' %}" title="#" >Trending</a></li>
                    {% if request.user.is_authenticated %}
                    <li class="hoverExtend "><a href="{% url 'story:recommended' %}" title="#" >Recommended</a></li>
                    {% endif %}
                    <li class="hoverExtend"><a href="{% url 'story:about' %}" title="#">About Us</a></li>
                    <li class="hoverExtend"><a href="{% url 'story:contact' %}" title="#">Contact Us</a></li>
                </ul>
                <!-- Search, Share, Language -->
                <ul class="nav navbar-nav navigation misc">
                    <li>
                        <a href="#" title="#" data-toggle="modal" data-target="#searchModal"><i class="fa fa-search"></i></a>
                    </li>
                    <li class="dropdown onHover">
                        <a href="#" title="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                            <i class="fa fa-share-alt"></i>
                        </a>
                        <!-- Social dropdown -->
                        <div class="dropdown-menu socials" role="menu">
                            <ul>
                                <li><a href="#" title="#" class="i"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#" title="#" class="i"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#" title="#" class="i"><i class="fa fa-google-plus"></i></a></li>
                                <li><a href="#" title="#" class="i"><i class="fa fa-linkedin"></i></a></li>
                                <li><a href="#" title="#" class="i"><i class="fa fa-pinterest-p"></i></a></li>
                                <li><a href="#" title="#" class="i"><i class="fa fa-tumblr"></i></a></li>
                                <li><a href="#" title="#" class="i"><i class="fa fa-envelope"></i></a></li>
                            </ul>
                        </div>
                    </li>
                    {% if not request.user.is_active %}
                        <li class="hoverExtend dropdown onHover fullwidth">
                            <a href="#" title="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Sign In/Up</a>

                            <!-- Templates dropdown -->
                            <div class="dropdown-menu layouts" role="menu">
                                <div class="row">
                                    <div class="col-xs-12 col-sm-12">
                                        <ul>
                                            <li><a href="{% url 'user:signin' %}" title="#"><i class="fa fa-sign-in icon"></i> Sign In</a></li>
                                            <li><a href="{% url 'user:signup' %}" title="#"><i class="fa fa-sign-in icon"></i> Sign Up</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </li>
                    {% else %}
                        <li class="hoverExtend dropdown onHover fullwidth">
                            <a href="#" title="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ request.user }}</a>

                            <!-- Templates dropdown -->
                            <div class="dropdown-menu layouts" role="menu">
                                <div class="row">
                                    <div class="col-xs-12 col-sm-12">
                                        <ul>
                                            <li><a href="{% url 'user:profile' request.user|slugify %}" title="#"><i class="fa fa-user icon"></i> Profile</a></li>
                                            <li><a href="{% url 'user:update' request.user|slugify %}" title="#"><i class="fa fa-edit icon"></i> Update</a></li>
                                            <li><a href="{% url 'story:create' request.user|slugify %}" title="#"><i class="fa fa-pencil icon"></i> Write</a></li>
                                            <hr/>
                                            <li><a href="{% url 'user:signout' %}" title="#"><i class="fa fa-sign-out icon"></i> Sign Out</a></li>

                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
    </div>

    <!-- Logo -->
    <div class="logoWrap">
        <div class="container">
            <h1>
                <a href="{% url 'story:index' %}" title="#">
                    <img src="{% static 'img/logo.png'%}" alt="#" width="208" height="108" class="img-responsive">
                    <strong>Blogee</strong>
                </a>
            </h1>
        </div>
    </div>
</header>
<div class="modal fade in" id="searchModal" tabindex="-1" role="dialog" aria-labelledby="searchModal" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <form method="GET" action='/home'>
                        <div class="c">
                            <input type="search" class="input" name='q' value="{{request.GET.q}}" placeholder="Type search term..." >
                            <button class="btn btn-color-full" type="submit"><span>Search</span></button>
                        </div>
                        <a href="#" title="#" class="advanced js-advanced-search"><span>Advanced search</span></a>
                        <div class="c advancedWrap container-fluid">
                            <div class="row">
                                <div class="col-sm-12 col-md-6 i">
                                    <select class="js-select" name='c'>
                                        <option>Story</option>
                                        <option>User</option>
                                        <option>Tags</option>
                                        <option>Categories</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>